

München	 <- "5ae7fe0b223bd8001928f6bf,59df62cfcec1f2000f263bbe,590e0b0a51d3460011c725c4,5a7855c029b729001a392170,5a454f6cdf5df2001aff8ed6,5b54905185381900195a1968"
Hamburg <-	"59622a7794f0520011c506d4,5a79937eb43907001b172bc2,5a44f07edf5df2001af6dd42,59c153c6d67eb5001108bc84,5991537e7e280a0010421ba7"
Hannover <-	"5ad382dc223bd80019088d99,59d6009866f66a001057590d,594c3c4cbe778200117baaf7"
Frankfurt <-	"5a4e7fdbc5fa910011130937,594ec6b2be7782001199758b,591cb99a51d3460011508f29,5b6ec06483ed9f0019460ce6"
Mainz <-	"5a9dbfb7bc2d410019563860,592c8c9751d3460011e9338b,5b51fdda8538190019ea7e99"
Wiesbaden	<- "58e3cd4aba2790001119a97f,58e6c1b8ba2790001135bd27,5b5b29b441718300190dfabb,5a4e63fec5fa910011103eb8"
Saarbruecken	<- "59835538e3b1fa001051cad5,5a535fd5fa02ec000ffdcce4,59205fd751d346001174a9d5,5a926ad0bc2d410019d42afa"
Berlin <- 	"592ca4b851d3460011ea2635,594c01c7be77820011792180,5b7b3bda2afec7001994f398,5a5ade44999d43001bb1efed"
Köln <-	"5996d4fad67eb500112def51,5a1b3c7d19991f0011b83054,59eb1c1249f6f80011a3ba91,5ab967ea850005001b95bb17"
Kaiserslautern <-	"5964fd9e94f0520011ec8da1,5aaac64e396417001b5b1195,5aa2f24b396417001b56de2d"
Karlsruhe <-	"580a3b97cd79a20011bf5b02,5985a081e3b1fa00107de064,5b4cf56d5dc1ec001b4f7eb3"
Stuttgart <-	"5af07d95223bd800197dfba4,5977bde9fe1c740011889f38,56a0de932cb6e1e41040a68b,59eb178c49f6f80011a361e6,5ad8c337223bd80019d059a8,5a81f33adc66ed00120db7c0"
Chemnitz <-	"5a8de4babc2d41001940cc5c,5a827f1edc66ed00121eaf26,590654eb5ba9e50011219266"
Leipzig <-	"59f492c350a2aa000f78b5dc,5b4706405dc1ec001b4aad4b,5b34e53c1fef04001bcec2b1,5ad6f0f3223bd800198ab0c9"
Rostock <-	"5a9c5387bc2d41001924872b,5ac37b76850005001bface69,59206a3b51d3460011750d4e,5b60739fd642ad0019d9e4c0"
Schwerin <-	"580771bacd79a20011b5c0cd,58fc7eca5ba9e50011bf1114"
Kiel <-	"5a85f03fbc2d4100194852bb,5904da3c5ba9e50011136682,5b5308bc853819001917f75c,58c89a56c519fa0011881e58"
Flensburg <-	"5ab1425c850005001b759302,5a94894fbc2d4100191a18dc,597b058dfe1c740011b96358"
Osnabrück	<- "5b354c901fef04001bdfc48b,599194197e280a001045eb00,59bec73dd67eb50011dc218c"
Münster <-	"5ae76e9a223bd80019136179,59c67b5ed67eb50011666dbb,5a30ea5375a96c000f012fe0,5b22736f1fef04001bd66707,5abd221b850005001b1aff35,5a0c30489fd3c20011115fb7,570bad2b45fd40c8197f13a2"
Oldenburg	<- "58f58343e617ed0011d4afc7,59342ee2ad0fa30011e85360,5b0a7aa04cd32e0019b64674,59342ee2ad0fa30011e85360"
Braunschweig <- 	"5a21a80f64434b0010b4793a,58e73c33ba279000113a756e"
Magdeburg <-	"581112710d07460012f1b36b,5b619e41d642ad00190d5496,599340c87e280a00105fdae1"
Regensburg <-	"599f0f24d67eb50011b5eb20,58d00131c877fb00118a494f"
Duesseldorf <-	"59ea646e49f6f8001195a3af,59763220fe1c740011719f1d,5ab79195850005001b5569d1.5a54ddc6fa02ec000f24306d,5ab141c6850005001b757da8"
aachn <- read.csv("./csv/Aachen.csv")
brln <- read.csv("./csv/Berlin.csv")
hmbrg <- read.csv("./csv/Hamburg.csv")
mnchn <- read.csv("./csv/Hamburg.csv")
brmn <- read.csv("./csv/Bremen.csv")
hnvr <- read.csv("./csv/Hannover.csv")
frkft <- read.csv("./csv/Frankfurt.csv")
mnz <- read.csv("./csv/Mainz.csv")
sbrk <- read.csv("./csv/Saarbrücken.csv")
ptsdm <- read.csv("./csv/Potsdam.csv")
bn <- read.csv("./csv/Bonn.csv")
mngl <- read.csv("./csv/MoenchenGladbach.csv")
wptl <- read.csv("./csv/Wuppertal.csv")
esn <- read.csv("./csv/Essen.csv")
dsbrg <- read.csv("./csv/Duisburg.csv")
drtm <- read.csv("./csv/Dortmund.csv")
kln <- read.csv("./csv/Koeln.csv")
kblnz <- read.csv("./csv/Koblenz.csv")
ksltrn <- read.csv("./csv/Kaiserslautern.csv")
krls <- read.csv("./csv/Karlsruhe.csv")
stgrt <- read.csv("./csv/Stuttgart.csv")
nrbrg <- read.csv("./csv/Nuernberg.csv")
cmnz <- read.csv("./csv/Chemnitz.csv")
lpz <- read.csv("./csv/Leipzig.csv")
rstk <- read.csv("./csv/Rostock.csv")
swrn <- read.csv("./csv/Schwerin.csv")
kl <- read.csv("./csv/Kiel.csv")
flnb <- read.csv("./csv/Flensburg.csv")
osna <- read.csv("./csv/Osnabrueck.csv")
mnstr <- read.csv("./csv/Muenster.csv")
bchm <- read.csv("./csv/Bochum.csv")
olbrg <- read.csv("./csv/Oldenburg.csv")
brnsc <- read.csv("./csv/Braunschweig.csv")
mgdb <- read.csv("./csv/Magdeburg.csv")
rgnbrg <- read.csv("./csv/Regensburg.csv")
dsdrf <- read.csv("./csv/Duesseldorf.csv")
blfld <- read.csv("./csv/Bielefeld.csv")
wsbn <- read.csv("./csv/Wiesbaden.csv")
temps <- "Temperatur"
feuchte <- "rel.%20Luftfeuchte"
Luftdruck <- "Luftdruck"
PM10 <- "PM10"
PM25 <- "PM2.5"
UV <- "UV-Intensität"
Helligkeit <- "Beleuchtungsstärke"

#Munch_temp <- get_stat_measurements(München, temps)
#write.csv(Munch_temp, "./csv/munch_t.csv")
#Munch_humi <- get_stat_measurements(München, feuchte)
#write.csv(Munch_humi, "./csv/munch_h.csv")
Munch_temp <- read.csv("./csv/munch_t.csv") %>% mutate(phenomena = "Temperatur")
Munch_humi <- read.csv("./csv/munch_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
Munch_th <- bind_rows(Munch_temp, Munch_humi) %>% group_by(phenomena)
#Munch_pm10 <- get_stat_measurements(München, PM10)
#write.csv(Munch_pm10, "./csv/munch_pm10.csv")
#Munch_pm25 <- get_stat_measurements(München, PM25)
#write.csv(Munch_pm25, "./csv/munch_pm25.csv")
Munch_pm10 <- read.csv("./csv/munch_10.csv") %>% mutate(phenomena = "PM10")
Munch_pm25 <- read.csv("./csv/munch_25.csv") %>% mutate(phenomena = "PM25")
Munch_pm <- bind_rows(Munch_pm10, Munch_pm25) %>% group_by(phenomena)
#Munch_dr <- get_stat_measurements(München, Luftdruck)
#write.csv(Munch_dr, "./csv/munch_dr.csv")
Munch_dr <- read.csv("./csv/munch_dr.csv") %>% mutate(phenomena = "Luftdruck")

#Munch_temps <- get_stat_measurements_si(München, temps)
#write.csv(Munch_temps, "./csv/munch_ts.csv")
#Munch_humis <- get_stat_measurements_si(München, feuchte)
#write.csv(Munch_humis, "./csv/munch_hs.csv")
Munch_temps <- read.csv("./csv/munch_ts.csv") %>% mutate(phenomena = "Temperatur")
Munch_humis <- read.csv("./csv/munch_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
Munch_ths <- bind_rows(Munch_temps, Munch_humis) %>% group_by(phenomena)
#Munch_pm10s <- get_stat_measurements_si(München, PM10)
#write.csv(Munch_pm10s, "./csv/munch_pm10s.csv")
#Munch_pm25s <- get_stat_measurements_si(München, PM25)
#write.csv(Munch_pm25s, "./csv/munch_pm25s.csv")
Munch_pm10s <- read.csv("./csv/munch_pm10s.csv") %>% mutate(phenomena = "PM10")
Munch_pm25s <- read.csv("./csv/munch_pm25s.csv") %>% mutate(phenomena = "PM25")
Munch_pms <- bind_rows(Munch_pm10s, Munch_pm25s) %>% group_by(phenomena)
#Munch_drs <- get_stat_measurements_si(München, Luftdruck)
#write.csv(Munch_drs, "./csv/munch_drs.csv")
Munch_drs <- read.csv("./csv/munch_drs.csv") %>% mutate(phenomena = "Luftdruck")


#ham_temp <- get_stat_measurements(Hamburg, temps)
#write.csv(ham_temp, "./csv/ham_t.csv")
#ham_humi <- get_stat_measurements(Hamburg, feuchte)
#write.csv(ham_humi, "./csv/ham_h.csv")
ham_temp <- read.csv("./csv/ham_t.csv") %>% mutate(phenomena = "Temperatur")
ham_humi <- read.csv("./csv/ham_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
ham_th <- bind_rows(ham_temp, ham_humi) %>% group_by(phenomena)
#ham_temp <- get_stat_measurements(Hamburg, PM10)
#ham_humi <- get_stat_measurements(Hamburg, PM25)
ham_pm10 <- read.csv("./csv/ham_10.csv") %>% mutate(phenomena = "PM10")
ham_pm25 <- read.csv("./csv/ham_25.csv") %>% mutate(phenomena = "PM25")
ham_pm <- bind_rows(ham_pm10, ham_pm25) %>% group_by(phenomena)
#ham_dr <- get_stat_measurements(Hamburg, Luftdruck)
#write.csv(ham_dr, "./csv/ham_dr.csv")
ham_dr <- read.csv("./csv/ham_dr.csv") %>% mutate(phenomena = "Luftdruck")

#ham_temps <- get_stat_measurements_si(Hamburg, temps)
#write.csv(ham_temps, "./csv/ham_ts.csv")
#ham_humis <- get_stat_measurements_si(Hamburg, feuchte)
#write.csv(ham_humis, "./csv/ham_hs.csv")
ham_temps <- read.csv("./csv/ham_ts.csv") %>% mutate(phenomena = "Temperatur")
ham_humis <- read.csv("./csv/ham_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
ham_ths <- bind_rows(ham_temps, ham_humis) %>% group_by(phenomena)
##ham_temps <- get_stat_measurements_si(Hamburg, PM10)
#ham_humis <- get_stat_measurements_si(Hamburg, PM25)
ham_pm10s <- read.csv("./csv/ham_10.csv") %>% mutate(phenomena = "PM10")
ham_pm25s <- read.csv("./csv/ham_25.csv") %>% mutate(phenomena = "PM25")
ham_pms <- bind_rows(ham_pm10, ham_pm25) %>% group_by(phenomena)
#ham_drs <- get_stat_measurements_si(Hamburg, Luftdruck)
#write.csv(ham_drs, "./csv/ham_drs.csv")
ham_drs <- read.csv("./csv/ham_drs.csv") %>% mutate(phenomena = "Luftdruck")





#han_temp <- get_stat_measurements(Hannover, temps)
#write.csv(han_temp, "./csv/han_t.csv")
#han_humi <- get_stat_measurements(Hannover, feuchte)
#write.csv(han_humi, "./csv/han_h.csv")
han_temp <- read.csv("./csv/han_t.csv") %>% mutate(phenomena = "Temperatur")
han_humi <- read.csv("./csv/han_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
han_th <- bind_rows(han_temp, han_humi) %>% group_by(phenomena)
#han_temp <- get_stat_measurements(Hannover, PM10)
#han_humi <- get_stat_measurements(Hannover, PM25)
han_pm10 <- read.csv("./csv/han_10.csv") %>% mutate(phenomena = "PM10")
han_pm25 <- read.csv("./csv/han_25.csv") %>% mutate(phenomena = "PM25")
han_pm <- bind_rows(han_pm10, han_pm25) %>% group_by(phenomena)
#han_dr <- get_stat_measurements(Hannover, Luftdruck)
#write.csv(han_dr, "./csv/han_dr.csv")
han_dr <- read.csv("./csv/han_dr.csv") %>% mutate(phenomena = "Luftdruck")

#han_temps <- get_stat_measurements_si(Hannover, temps)
#write.csv(han_temps, "./csv/han_ts.csv")
#han_humis <- get_stat_measurements_si(Hannover, feuchte)
#write.csv(han_humis, "./csv/han_hs.csv")
han_temps <- read.csv("./csv/han_ts.csv") %>% mutate(phenomena = "Temperatur")
han_humis <- read.csv("./csv/han_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
han_ths <- bind_rows(han_temps, han_humis) %>% group_by(phenomena)
#han_temps <- get_stat_measurements_si(Hannover, PM10)
#han_humis <- get_stat_measurements_si(Hannover, PM25)
han_pm10s <- read.csv("./csv/han_10.csv") %>% mutate(phenomena = "PM10")
han_pm25s <- read.csv("./csv/han_25.csv") %>% mutate(phenomena = "PM25")
han_pms <- bind_rows(han_pm10, han_pm25) %>% group_by(phenomena)
#han_drs <- get_stat_measurements_si(Hannover, Luftdruck)
#write.csv(han_drs, "./csv/han_drs.csv")
han_drs <- read.csv("./csv/han_drs.csv") %>% mutate(phenomena = "Luftdruck")

#fra_temp <- get_stat_measurements(Frankfurt, temps)
#write.csv(fra_temp, "./csv/fra_t.csv")
#fra_humi <- get_stat_measurements(Frankfurt, feuchte)
#write.csv(fra_humi, "./csv/fra_h.csv")
fra_temp <- read.csv("./csv/fra_t.csv") %>% mutate(phenomena = "Temperatur")
fra_humi <- read.csv("./csv/fra_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
fra_th <- bind_rows(fra_temp, fra_humi) %>% group_by(phenomena)
#fra_temp <- get_stat_measurements(Frankfurt, PM10)
#fra_humi <- get_stat_measurements(Frankfurt, PM25)
fra_pm10 <- read.csv("./csv/fra_10.csv") %>% mutate(phenomena = "PM10")
fra_pm25 <- read.csv("./csv/fra_25.csv") %>% mutate(phenomena = "PM25")
fra_pm <- bind_rows(fra_pm10, fra_pm25) %>% group_by(phenomena)
#fra_dr <- get_stat_measurements(Frankfurt, Luftdruck)
#write.csv(fra_dr, "./csv/fra_dr.csv")
#fra_dr <- read.csv("./csv/fra_dr.csv") %>% mutate(phenomena = "Luftdruck")

#fra_temps <- get_stat_measurements_si(Frankfurt, temps)
#write.csv(fra_temps, "./csv/fra_ts.csv")
#fra_humis <- get_stat_measurements_si(Frankfurt, feuchte)
#write.csv(fra_humis, "./csv/fra_hs.csv")
fra_temps <- read.csv("./csv/fra_ts.csv") %>% mutate(phenomena = "Temperatur")
fra_humis <- read.csv("./csv/fra_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
fra_ths <- bind_rows(fra_temps, fra_humis) %>% group_by(phenomena)
#fra_temps <- get_stat_measurements_si(Frankfurt, PM10)
#fra_humis <- get_stat_measurements_si(Frankfurt, PM25)
fra_pm10s <- read.csv("./csv/fra_10.csv") %>% mutate(phenomena = "PM10")
fra_pm25s <- read.csv("./csv/fra_25.csv") %>% mutate(phenomena = "PM25")
fra_pms <- bind_rows(fra_pm10, fra_pm25) %>% group_by(phenomena)
#fra_drs <- get_stat_measurements_si(Frankfurt, Luftdruck)
#write.csv(fra_drs, "./csv/fra_drs.csv")
#fra_drs <- read.csv("./csv/fra_drs.csv") %>% mutate(phenomena = "Luftdruck")


#muns_temp <- get_stat_measurements(Münster, temps)
#write.csv(muns_temp, "./csv/muns_t.csv")
#muns_humi <- get_stat_measurements(Münster, feuchte)
#write.csv(muns_humi, "./csv/muns_h.csv")
muns_temp <- read.csv("./csv/muns_t.csv") %>% mutate(phenomena = "Temperatur")
muns_humi <- read.csv("./csv/muns_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
muns_th <- bind_rows(muns_temp, muns_humi) %>% group_by(phenomena)
#muns_temp <- get_stat_measurements(Münster, PM10)
#muns_humi <- get_stat_measurements(Münster, PM25)
muns_pm10 <- read.csv("./csv/muns_10.csv") %>% mutate(phenomena = "PM10")
muns_pm25 <- read.csv("./csv/muns_25.csv") %>% mutate(phenomena = "PM25")
muns_pm <- bind_rows(muns_pm10, muns_pm25) %>% group_by(phenomena)
#muns_dr <- get_stat_measurements(Münster, Luftdruck)
#write.csv(muns_dr, "./csv/muns_dr.csv")
muns_dr <- read.csv("./csv/muns_dr.csv") %>% mutate(phenomena = "Luftdruck")

#muns_temps <- get_stat_measurements_si(Münster, temps)
#write.csv(muns_temps, "./csv/muns_ts.csv")
#muns_humis <- get_stat_measurements_si(Münster, feuchte)
#write.csv(muns_humis, "./csv/muns_hs.csv")
muns_temps <- read.csv("./csv/muns_ts.csv") %>% mutate(phenomena = "Temperatur")
muns_humis <- read.csv("./csv/muns_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
muns_ths <- bind_rows(muns_temps, muns_humis) %>% group_by(phenomena)
#muns_temps <- get_stat_measurements_si(Münster, PM10)
#muns_humis <- get_stat_measurements_si(Münster, PM25)
write.csv(muns_humi, "./csv/muns_hs.csv")
write.csv(muns_humis, "./csv/muns_hs.csv")
muns_pm10s <- read.csv("./csv/muns_10.csv") %>% mutate(phenomena = "PM10")
muns_pm25s <- read.csv("./csv/muns_25.csv") %>% mutate(phenomena = "PM25")

muns_pms <- bind_rows(muns_pm10, muns_pm25) %>% group_by(phenomena)
#muns_drs <- get_stat_measurements_si(Münster, Luftdruck)
#write.csv(muns_drs, "./csv/muns_drs.csv")
muns_drs <- read.csv("./csv/muns_drs.csv") %>% mutate(phenomena = "Luftdruck")




#ber_temp <- get_stat_measurements(Berlin, temps)
#write.csv(ber_temp, "./csv/ber_t.csv")
#ber_humi <- get_stat_measurements(Berlin, feuchte)
#write.csv(ber_humi, "./csv/ber_h.csv")
ber_temp <- read.csv("./csv/ber_t.csv") %>% mutate(phenomena = "Temperatur")
ber_humi <- read.csv("./csv/ber_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
ber_th <- bind_rows(ber_temp, ber_humi) %>% group_by(phenomena)
#ber_temp <- get_stat_measurements(Berlin, PM10)
#ber_humi <- get_stat_measurements(Berlin, PM25)
ber_pm10 <- read.csv("./csv/ber_10.csv") %>% mutate(phenomena = "PM10")
ber_pm25 <- read.csv("./csv/ber_25.csv") %>% mutate(phenomena = "PM25")
ber_pm <- bind_rows(ber_pm10, ber_pm25) %>% group_by(phenomena)
#ber_dr <- get_stat_measurements(Berlin, Luftdruck)
#write.csv(ber_dr, "./csv/ber_dr.csv")
ber_dr <- read.csv("./csv/ber_dr.csv") %>% mutate(phenomena = "Luftdruck")

#ber_temps <- get_stat_measurements_si(Berlin, temps)
#write.csv(ber_temps, "./csv/ber_ts.csv")
#ber_humis <- get_stat_measurements_si(Berlin, feuchte)
#write.csv(ber_humis, "./csv/ber_hs.csv")
ber_temps <- read.csv("./csv/ber_ts.csv") %>% mutate(phenomena = "Temperatur")
ber_humis <- read.csv("./csv/ber_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
ber_ths <- bind_rows(ber_temps, ber_humis) %>% group_by(phenomena)
#ber_temps <- get_stat_measurements_si(Berlin, PM10)
#ber_humis <- get_stat_measurements_si(Berlin, PM25)
ber_pm10s <- read.csv("./csv/ber_10.csv") %>% mutate(phenomena = "PM10")
ber_pm25s <- read.csv("./csv/ber_25.csv") %>% mutate(phenomena = "PM25")
ber_pms <- bind_rows(ber_pm10, ber_pm25) %>% group_by(phenomena)
#ber_drs <- get_stat_measurements_si(Berlin, Luftdruck)
#write.csv(ber_drs, "./csv/ber_drs.csv")
ber_drs <- read.csv("./csv/ber_drs.csv") %>% mutate(phenomena = "Luftdruck")



#kol_temp <- get_stat_measurements(Köln, temps)
#write.csv(kol_temp, "./csv/kol_t.csv")
#kol_humi <- get_stat_measurements(Köln, feuchte)
#write.csv(kol_humi, "./csv/kol_h.csv")
kol_temp <- read.csv("./csv/kol_t.csv") %>% mutate(phenomena = "Temperatur")
kol_humi <- read.csv("./csv/kol_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
kol_th <- bind_rows(kol_temp, kol_humi) %>% group_by(phenomena)
#kol_temp <- get_stat_measurements(Köln, PM10)
#kol_humi <- get_stat_measurements(Köln, PM25)
kol_pm10 <- read.csv("./csv/kol_10.csv") %>% mutate(phenomena = "PM10")
kol_pm25 <- read.csv("./csv/kol_25.csv") %>% mutate(phenomena = "PM25")
kol_pm <- bind_rows(kol_pm10, kol_pm25) %>% group_by(phenomena)
#kol_dr <- get_stat_measurements(Köln, Luftdruck)
#write.csv(kol_dr, "./csv/kol_dr.csv")
kol_dr <- read.csv("./csv/kol_dr.csv") %>% mutate(phenomena = "Luftdruck")

#kol_temps <- get_stat_measurements_si(Köln, temps)
#write.csv(kol_temps, "./csv/kol_ts.csv")
#kol_humis <- get_stat_measurements_si(Köln, feuchte)
#write.csv(kol_humis, "./csv/kol_hs.csv")
kol_temps <- read.csv("./csv/kol_ts.csv") %>% mutate(phenomena = "Temperatur")
kol_humis <- read.csv("./csv/kol_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
kol_ths <- bind_rows(kol_temps, kol_humis) %>% group_by(phenomena)
#kol_temps <- get_stat_measurements_si(Köln, PM10)
#kol_humis <- get_stat_measurements_si(Köln, PM25)
kol_pm10s <- read.csv("./csv/kol_10.csv") %>% mutate(phenomena = "PM10")
kol_pm25s <- read.csv("./csv/kol_25.csv") %>% mutate(phenomena = "PM25")
kol_pms <- bind_rows(kol_pm10, kol_pm25) %>% group_by(phenomena)
#kol_drs <- get_stat_measurements_si(Köln, Luftdruck)
#write.csv(kol_drs, "./csv/kol_drs.csv")
kol_drs <- read.csv("./csv/kol_drs.csv") %>% mutate(phenomena = "Luftdruck")

#stu_temp <- get_stat_measurements(Stuttgart, temps)
#write.csv(stu_temp, "./csv/stu_t.csv")
#stu_humi <- get_stat_measurements(Stuttgart, feuchte)
#write.csv(stu_humi, "./csv/stu_h.csv")
stu_temp <- read.csv("./csv/stu_t.csv") %>% mutate(phenomena = "Temperatur")
stu_humi <- read.csv("./csv/stu_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
stu_th <- bind_rows(stu_temp, stu_humi) %>% group_by(phenomena)
#stu_temp <- get_stat_measurements(Stuttgart, PM10)
#stu_humi <- get_stat_measurements(Stuttgart, PM25)
stu_pm10 <- read.csv("./csv/stu_10.csv") %>% mutate(phenomena = "PM10")
stu_pm25 <- read.csv("./csv/stu_25.csv") %>% mutate(phenomena = "PM25")
stu_pm <- bind_rows(stu_pm10, stu_pm25) %>% group_by(phenomena)
#stu_dr <- get_stat_measurements(Stuttgart, Luftdruck)
#write.csv(stu_dr, "./csv/stu_dr.csv")
stu_dr <- read.csv("./csv/stu_dr.csv") %>% mutate(phenomena = "Luftdruck")

#stu_temps <- get_stat_measurements_si(Stuttgart, temps)
#write.csv(stu_temps, "./csv/stu_ts.csv")
#stu_humis <- get_stat_measurements_si(Stuttgart, feuchte)
#write.csv(stu_humis, "./csv/stu_hs.csv")
stu_temps <- read.csv("./csv/stu_ts.csv") %>% mutate(phenomena = "Temperatur")
stu_humis <- read.csv("./csv/stu_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
stu_ths <- bind_rows(stu_temps, stu_humis) %>% group_by(phenomena)
#stu_temps <- get_stat_measurements_si(Stuttgart, PM10)
#stu_humis <- get_stat_measurements_si(Stuttgart, PM25)
stu_pm10s <- read.csv("./csv/stu_10.csv") %>% mutate(phenomena = "PM10")
stu_pm25s <- read.csv("./csv/stu_25.csv") %>% mutate(phenomena = "PM25")
stu_pms <- bind_rows(stu_pm10, stu_pm25) %>% group_by(phenomena)
#stu_drs <- get_stat_measurements_si(Stuttgart, Luftdruck)
#write.csv(stu_drs, "./csv/stu_drs.csv")
stu_drs <- read.csv("./csv/stu_drs.csv") %>% mutate(phenomena = "Luftdruck")



#klt_temp <- get_stat_measurements(Kaiserslautern, temps)
#write.csv(klt_temp, "./csv/klt_t.csv")
#klt_humi <- get_stat_measurements(Kaiserslautern, feuchte)
#write.csv(klt_humi, "./csv/klt_h.csv")
klt_temp <- read.csv("./csv/klt_t.csv") %>% mutate(phenomena = "Temperatur")
klt_humi <- read.csv("./csv/klt_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
klt_th <- bind_rows(klt_temp, klt_humi) %>% group_by(phenomena)
#klt_temp <- get_stat_measurements(Kaiserslautern, PM10)
#klt_humi <- get_stat_measurements(Kaiserslautern, PM25)
klt_pm10 <- read.csv("./csv/klt_10.csv") %>% mutate(phenomena = "PM10")
klt_pm25 <- read.csv("./csv/klt_25.csv") %>% mutate(phenomena = "PM25")
klt_pm <- bind_rows(klt_pm10, klt_pm25) %>% group_by(phenomena)
#klt_dr <- get_stat_measurements(Kaiserslautern, Luftdruck)
#write.csv(klt_dr, "./csv/klt_dr.csv")
klt_dr <- read.csv("./csv/klt_dr.csv") %>% mutate(phenomena = "Luftdruck")

#klt_temps <- get_stat_measurements_si(Kaiserslautern, temps)
#write.csv(klt_temps, "./csv/klt_ts.csv")
#klt_humis <- get_stat_measurements_si(Kaiserslautern, feuchte)
#write.csv(klt_humis, "./csv/klt_hs.csv")
klt_temps <- read.csv("./csv/klt_ts.csv") %>% mutate(phenomena = "Temperatur")
klt_humis <- read.csv("./csv/klt_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
klt_ths <- bind_rows(klt_temps, klt_humis) %>% group_by(phenomena)
#klt_temps <- get_stat_measurements_si(Kaiserslautern, PM10)
#klt_humis <- get_stat_measurements_si(Kaiserslautern, PM25)
klt_pm10s <- read.csv("./csv/klt_10.csv") %>% mutate(phenomena = "PM10")
klt_pm25s <- read.csv("./csv/klt_25.csv") %>% mutate(phenomena = "PM25")
klt_pms <- bind_rows(klt_pm10, klt_pm25) %>% group_by(phenomena)
#klt_drs <- get_stat_measurements_si(Kaiserslautern, Luftdruck)
#write.csv(klt_drs, "./csv/klt_drs.csv")
klt_drs <- read.csv("./csv/klt_drs.csv") %>% mutate(phenomena = "Luftdruck")


#lpz_temp <- get_stat_measurements(Leipzig, temps)
#write.csv(lpz_temp, "./csv/lpz_t.csv")
#lpz_humi <- get_stat_measurements(Leipzig, feuchte)
#write.csv(lpz_humi, "./csv/lpz_h.csv")
lpz_temp <- read.csv("./csv/lpz_t.csv") %>% mutate(phenomena = "Temperatur")
lpz_humi <- read.csv("./csv/lpz_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
lpz_th <- bind_rows(lpz_temp, lpz_humi) %>% group_by(phenomena)
#lpz_temp <- get_stat_measurements(Leipzig, PM10)
#lpz_humi <- get_stat_measurements(Leipzig, PM25)
lpz_pm10 <- read.csv("./csv/lpz_10.csv") %>% mutate(phenomena = "PM10")
lpz_pm25 <- read.csv("./csv/lpz_25.csv") %>% mutate(phenomena = "PM25")
lpz_pm <- bind_rows(lpz_pm10, lpz_pm25) %>% group_by(phenomena)
#lpz_dr <- get_stat_measurements(Leipzig, Luftdruck)
#write.csv(lpz_dr, "./csv/lpz_dr.csv")
lpz_dr <- read.csv("./csv/lpz_dr.csv") %>% mutate(phenomena = "Luftdruck")

#lpz_temps <- get_stat_measurements_si(Leipzig, temps)
#write.csv(lpz_temps, "./csv/lpz_ts.csv")
#lpz_humis <- get_stat_measurements_si(Leipzig, feuchte)
#write.csv(lpz_humis, "./csv/lpz_hs.csv")
lpz_temps <- read.csv("./csv/lpz_ts.csv") %>% mutate(phenomena = "Temperatur")
lpz_humis <- read.csv("./csv/lpz_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
lpz_ths <- bind_rows(lpz_temps, lpz_humis) %>% group_by(phenomena)
#lpz_temps <- get_stat_measurements_si(Leipzig, PM10)
#lpz_humis <- get_stat_measurements_si(Leipzig, PM25)
lpz_pm10s <- read.csv("./csv/lpz_10.csv") %>% mutate(phenomena = "PM10")
lpz_pm25s <- read.csv("./csv/lpz_25.csv") %>% mutate(phenomena = "PM25")
lpz_pms <- bind_rows(lpz_pm10, lpz_pm25) %>% group_by(phenomena)
#lpz_drs <- get_stat_measurements_si(Leipzig, Luftdruck)
#write.csv(lpz_drs, "./csv/lpz_drs.csv")
lpz_drs <- read.csv("./csv/lpz_drs.csv") %>% mutate(phenomena = "Luftdruck")



#old_temp <- get_stat_measurements(Oldenburg, temps)
#write.csv(old_temp, "./csv/old_t.csv")
#old_humi <- get_stat_measurements(Oldenburg, feuchte)
#write.csv(old_humi, "./csv/old_h.csv")
old_temp <- read.csv("./csv/old_t.csv") %>% mutate(phenomena = "Temperatur")
old_humi <- read.csv("./csv/old_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
old_th <- bind_rows(old_temp, old_humi) %>% group_by(phenomena)
#old_temp <- get_stat_measurements(Oldenburg, PM10)
#old_humi <- get_stat_measurements(Oldenburg, PM25)
old_pm10 <- read.csv("./csv/old_10.csv") %>% mutate(phenomena = "PM10")
old_pm25 <- read.csv("./csv/old_25.csv") %>% mutate(phenomena = "PM25")
old_pm <- bind_rows(old_pm10, old_pm25) %>% group_by(phenomena)
#old_dr <- get_stat_measurements(Oldenburg, Luftdruck)
#write.csv(old_dr, "./csv/old_dr.csv")
#old_dr <- read.csv("./csv/old_dr.csv") %>% mutate(phenomena = "Luftdruck")

#old_temps <- get_stat_measurements_si(Oldenburg, temps)
#write.csv(old_temps, "./csv/old_ts.csv")
#old_humis <- get_stat_measurements_si(Oldenburg, feuchte)
#write.csv(old_humis, "./csv/old_hs.csv")
old_temps <- read.csv("./csv/old_ts.csv") %>% mutate(phenomena = "Temperatur")
old_humis <- read.csv("./csv/old_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
old_ths <- bind_rows(old_temps, old_humis) %>% group_by(phenomena)
#old_temps <- get_stat_measurements_si(Oldenburg, PM10)
#old_humis <- get_stat_measurements_si(Oldenburg, PM25)
old_pm10s <- read.csv("./csv/old_10.csv") %>% mutate(phenomena = "PM10")
old_pm25s <- read.csv("./csv/old_25.csv") %>% mutate(phenomena = "PM25")
old_pms <- bind_rows(old_pm10, old_pm25) %>% group_by(phenomena)
#old_drs <- get_stat_measurements_si(Oldenburg, Luftdruck)
#write.csv(old_drs, "./csv/old_drs.csv")
#old_drs <- read.csv("./csv/old_drs.csv") %>% mutate(phenomena = "Luftdruck")



#ros_temp <- get_stat_measurements(Rostock, temps)
#write.csv(ros_temp, "./csv/ros_t.csv")
#ros_humi <- get_stat_measurements(Rostock, feuchte)
#write.csv(ros_humi, "./csv/ros_h.csv")
ros_temp <- read.csv("./csv/ros_t.csv") %>% mutate(phenomena = "Temperatur")
ros_humi <- read.csv("./csv/ros_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
ros_th <- bind_rows(ros_temp, ros_humi) %>% group_by(phenomena)
#ros_temp <- get_stat_measurements(Rostock, PM10)
#ros_humi <- get_stat_measurements(Rostock, PM25)
ros_pm10 <- read.csv("./csv/ros_10.csv") %>% mutate(phenomena = "PM10")
ros_pm25 <- read.csv("./csv/ros_25.csv") %>% mutate(phenomena = "PM25")
ros_pm <- bind_rows(ros_pm10, ros_pm25) %>% group_by(phenomena)
#ros_dr <- get_stat_measurements(Rostock, Luftdruck)
#write.csv(ros_dr, "./csv/ros_dr.csv")
#ros_dr <- read.csv("./csv/ros_dr.csv") %>% mutate(phenomena = "Luftdruck")

#ros_temps <- get_stat_measurements_si(Rostock, temps)
#write.csv(ros_temps, "./csv/ros_ts.csv")
#ros_humis <- get_stat_measurements_si(Rostock, feuchte)
#write.csv(ros_humis, "./csv/ros_hs.csv")
ros_temps <- read.csv("./csv/ros_ts.csv") %>% mutate(phenomena = "Temperatur")
ros_humis <- read.csv("./csv/ros_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
ros_ths <- bind_rows(ros_temps, ros_humis) %>% group_by(phenomena)
#ros_temps <- get_stat_measurements_si(Rostock, PM10)
#ros_humis <- get_stat_measurements_si(Rostock, PM25)
ros_pm10s <- read.csv("./csv/ros_10.csv") %>% mutate(phenomena = "PM10")
ros_pm25s <- read.csv("./csv/ros_25.csv") %>% mutate(phenomena = "PM25")
ros_pms <- bind_rows(ros_pm10, ros_pm25) %>% group_by(phenomena)
#ros_drs <- get_stat_measurements_si(Rostock, Luftdruck)
#write.csv(ros_drs, "./csv/ros_drs.csv")
#ros_drs <- read.csv("./csv/ros_drs.csv") %>% mutate(phenomena = "Luftdruck")


#sar_temp <- get_stat_measurements(Saarbruecken, temps)
#write.csv(sar_temp, "./csv/sar_t.csv")
#sar_humi <- get_stat_measurements(Saarbruecken, feuchte)
#write.csv(sar_humi, "./csv/sar_h.csv")
sar_temp <- read.csv("./csv/sar_t.csv") %>% mutate(phenomena = "Temperatur")
sar_humi <- read.csv("./csv/sar_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
sar_th <- bind_rows(sar_temp, sar_humi) %>% group_by(phenomena)
#sar_temp <- get_stat_measurements(Saarbruecken, PM10)
#sar_humi <- get_stat_measurements(Saarbruecken, PM25)
sar_pm10 <- read.csv("./csv/sar_10.csv") %>% mutate(phenomena = "PM10")
sar_pm25 <- read.csv("./csv/sar_25.csv") %>% mutate(phenomena = "PM25")
sar_pm <- bind_rows(sar_pm10, sar_pm25) %>% group_by(phenomena)
#sar_dr <- get_stat_measurements(Saarbruecken, Luftdruck)
#write.csv(sar_dr, "./csv/sar_dr.csv")
#sar_dr <- read.csv("./csv/sar_dr.csv") %>% mutate(phenomena = "Luftdruck")

#sar_temps <- get_stat_measurements_si(Saarbruecken, temps)
#write.csv(sar_temps, "./csv/sar_ts.csv")
#sar_humis <- get_stat_measurements_si(Saarbruecken, feuchte)
#write.csv(sar_humis, "./csv/sar_hs.csv")
sar_temps <- read.csv("./csv/sar_ts.csv") %>% mutate(phenomena = "Temperatur")
sar_humis <- read.csv("./csv/sar_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
sar_ths <- bind_rows(sar_temps, sar_humis) %>% group_by(phenomena)
#sar_temps <- get_stat_measurements_si(Saarbruecken, PM10)
#sar_humis <- get_stat_measurements_si(Saarbruecken, PM25)
sar_pm10s <- read.csv("./csv/sar_10.csv") %>% mutate(phenomena = "PM10")
sar_pm25s <- read.csv("./csv/sar_25.csv") %>% mutate(phenomena = "PM25")
sar_pms <- bind_rows(sar_pm10, sar_pm25) %>% group_by(phenomena)
#sar_drs <- get_stat_measurements_si(Saarbruecken, Luftdruck)
#write.csv(sar_drs, "./csv/sar_drs.csv")
#sar_drs <- read.csv("./csv/sar_drs.csv") %>% mutate(phenomena = "Luftdruck")


#che_temp <- get_stat_measurements(Chemnitz, temps)
#write.csv(che_temp, "./csv/che_t.csv")
#che_humi <- get_stat_measurements(Chemnitz, feuchte)
#write.csv(che_humi, "./csv/che_h.csv")
che_temp <- read.csv("./csv/che_t.csv") %>% mutate(phenomena = "Temperatur")
che_humi <- read.csv("./csv/che_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
che_th <- bind_rows(che_temp, che_humi) %>% group_by(phenomena)
#che_temp <- get_stat_measurements(Chemnitz, PM10)
#che_humi <- get_stat_measurements(Chemnitz, PM25)
che_pm10 <- read.csv("./csv/che_10.csv") %>% mutate(phenomena = "PM10")
che_pm25 <- read.csv("./csv/che_25.csv") %>% mutate(phenomena = "PM25")
che_pm <- bind_rows(che_pm10, che_pm25) %>% group_by(phenomena)
#che_dr <- get_stat_measurements(Chemnitz, Luftdruck)
#write.csv(che_dr, "./csv/che_dr.csv")
che_dr <- read.csv("./csv/che_dr.csv") %>% mutate(phenomena = "Luftdruck")

#che_temps <- get_stat_measurements_si(Chemnitz, temps)
#write.csv(che_temps, "./csv/che_ts.csv")
#che_humis <- get_stat_measurements_si(Chemnitz, feuchte)
#write.csv(che_humis, "./csv/che_hs.csv")
che_temps <- read.csv("./csv/che_ts.csv") %>% mutate(phenomena = "Temperatur")
che_humis <- read.csv("./csv/che_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
che_ths <- bind_rows(che_temps, che_humis) %>% group_by(phenomena)
#che_temps <- get_stat_measurements_si(Chemnitz, PM10)
#che_humis <- get_stat_measurements_si(Chemnitz, PM25)
che_pm10s <- read.csv("./csv/che_10.csv") %>% mutate(phenomena = "PM10")
che_pm25s <- read.csv("./csv/che_25.csv") %>% mutate(phenomena = "PM25")
che_pms <- bind_rows(che_pm10, che_pm25) %>% group_by(phenomena)
#che_drs <- get_stat_measurements_si(Chemnitz, Luftdruck)
#write.csv(che_drs, "./csv/che_drs.csv")
che_drs <- read.csv("./csv/che_drs.csv") %>% mutate(phenomena = "Luftdruck")


#kl_temp <- get_stat_measurements(Kiel, temps)
#write.csv(kl_temp, "./csv/kl_t.csv")
#kl_humi <- get_stat_measurements(Kiel, feuchte)
#write.csv(kl_humi, "./csv/kl_h.csv")
kl_temp <- read.csv("./csv/kl_t.csv") %>% mutate(phenomena = "Temperatur")
kl_humi <- read.csv("./csv/kl_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
kl_th <- bind_rows(kl_temp, kl_humi) %>% group_by(phenomena)
#kl_temp <- get_stat_measurements(Kiel, PM10)
#kl_humi <- get_stat_measurements(Kiel, PM25)
kl_pm10 <- read.csv("./csv/kl_10.csv") %>% mutate(phenomena = "PM10")
kl_pm25 <- read.csv("./csv/kl_25.csv") %>% mutate(phenomena = "PM25")
kl_pm <- bind_rows(kl_pm10, kl_pm25) %>% group_by(phenomena)
#kl_dr <- get_stat_measurements(Kiel, Luftdruck)
#write.csv(kl_dr, "./csv/kl_dr.csv")
kl_dr <- read.csv("./csv/kl_dr.csv") %>% mutate(phenomena = "Luftdruck")

#kl_temps <- get_stat_measurements_si(Kiel, temps)
#write.csv(kl_temps, "./csv/kl_ts.csv")
#kl_humis <- get_stat_measurements_si(Kiel, feuchte)
#write.csv(kl_humis, "./csv/kl_hs.csv")
kl_temps <- read.csv("./csv/kl_ts.csv") %>% mutate(phenomena = "Temperatur")
kl_humis <- read.csv("./csv/kl_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
kl_ths <- bind_rows(kl_temps, kl_humis) %>% group_by(phenomena)
#kl_temps <- get_stat_measurements_si(Kiel, PM10)
#kl_humis <- get_stat_measurements_si(Kiel, PM25)
kl_pm10s <- read.csv("./csv/kl_10.csv") %>% mutate(phenomena = "PM10")
kl_pm25s <- read.csv("./csv/kl_25.csv") %>% mutate(phenomena = "PM25")
kl_pms <- bind_rows(kl_pm10, kl_pm25) %>% group_by(phenomena)
#kl_drs <- get_stat_measurements_si(Kiel, Luftdruck)
#write.csv(kl_drs, "./csv/kl_drs.csv")
kl_drs <- read.csv("./csv/kl_drs.csv") %>% mutate(phenomena = "Luftdruck")



#osna_temp <- get_stat_measurements(Osnabrück, temps)
#write.csv(osna_temp, "./csv/osna_t.csv")
#osna_humi <- get_stat_measurements(Osnabrück, feuchte)
#write.csv(osna_humi, "./csv/osna_h.csv")
osna_temp <- read.csv("./csv/osna_t.csv") %>% mutate(phenomena = "Temperatur")
osna_humi <- read.csv("./csv/osna_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
osna_th <- bind_rows(osna_temp, osna_humi) %>% group_by(phenomena)
##osna_temp <- get_stat_measurements(Osnabrück, PM10)
#osna_humi <- get_stat_measurements(Osnabrück, PM25)
osna_pm10 <- read.csv("./csv/osna_10.csv") %>% mutate(phenomena = "PM10")
osna_pm25 <- read.csv("./csv/osna_25.csv") %>% mutate(phenomena = "PM25")
osna_pm <- bind_rows(osna_pm10, osna_pm25) %>% group_by(phenomena)
#osna_dr <- get_stat_measurements(Osnabrück, Luftdruck)
#write.csv(osna_dr, "./csv/osna_dr.csv")
osna_dr <- read.csv("./csv/osna_dr.csv") %>% mutate(phenomena = "Luftdruck")

#osna_temps <- get_stat_measurements_si(Osnabrück, temps)
#write.csv(osna_temps, "./csv/osna_ts.csv")
#osna_humis <- get_stat_measurements_si(Osnabrück, feuchte)
#write.csv(osna_humis, "./csv/osna_hs.csv")
osna_temps <- read.csv("./csv/osna_ts.csv") %>% mutate(phenomena = "Temperatur")
osna_humis <- read.csv("./csv/osna_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
osna_ths <- bind_rows(osna_temps, osna_humis) %>% group_by(phenomena)
#osna_temps <- get_stat_measurements_si(Osnabrück, PM10)
#osna_humis <- get_stat_measurements_si(Osnabrück, PM25)
osna_pm10s <- read.csv("./csv/osna_10.csv") %>% mutate(phenomena = "PM10")
osna_pm25s <- read.csv("./csv/osna_25.csv") %>% mutate(phenomena = "PM25")
osna_pms <- bind_rows(osna_pm10, osna_pm25) %>% group_by(phenomena)
#osna_drs <- get_stat_measurements_si(Osnabrück, Luftdruck)
#write.csv(osna_drs, "./csv/osna_drs.csv")
osna_drs <- read.csv("./csv/osna_drs.csv") %>% mutate(phenomena = "Luftdruck")


#mag_temp <- get_stat_measurements(Magdeburg, temps)
#write.csv(mag_temp, "./csv/mag_t.csv")
#mag_humi <- get_stat_measurements(Magdeburg, feuchte)
#write.csv(mag_humi, "./csv/mag_h.csv")
mag_temp <- read.csv("./csv/mag_t.csv") %>% mutate(phenomena = "Temperatur")
mag_humi <- read.csv("./csv/mag_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
mag_th <- bind_rows(mag_temp, mag_humi) %>% group_by(phenomena)
#mag_temp <- get_stat_measurements(Magdeburg, PM10)
#mag_humi <- get_stat_measurements(Magdeburg, PM25)
mag_pm10 <- read.csv("./csv/mag_10.csv") %>% mutate(phenomena = "PM10")
mag_pm25 <- read.csv("./csv/mag_25.csv") %>% mutate(phenomena = "PM25")
mag_pm <- bind_rows(mag_pm10, mag_pm25) %>% group_by(phenomena)
#mag_dr <- get_stat_measurements(Magdeburg, Luftdruck)
#write.csv(mag_dr, "./csv/mag_dr.csv")
mag_dr <- read.csv("./csv/mag_dr.csv") %>% mutate(phenomena = "Luftdruck")

#mag_temps <- get_stat_measurements_si(Magdeburg, temps)
#write.csv(mag_temps, "./csv/mag_ts.csv")
#mag_humis <- get_stat_measurements_si(Magdeburg, feuchte)
#write.csv(mag_humis, "./csv/mag_hs.csv")
mag_temps <- read.csv("./csv/mag_ts.csv") %>% mutate(phenomena = "Temperatur")
mag_humis <- read.csv("./csv/mag_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
mag_ths <- bind_rows(mag_temps, mag_humis) %>% group_by(phenomena)
#mag_temps <- get_stat_measurements_si(Magdeburg, PM10)
#mag_humis <- get_stat_measurements_si(Magdeburg, PM25)
mag_pm10s <- read.csv("./csv/mag_10.csv") %>% mutate(phenomena = "PM10")
mag_pm25s <- read.csv("./csv/mag_25.csv") %>% mutate(phenomena = "PM25")
mag_pms <- bind_rows(mag_pm10, mag_pm25) %>% group_by(phenomena)
#mag_drs <- get_stat_measurements_si(Magdeburg, Luftdruck)
#write.csv(mag_drs, "./csv/mag_drs.csv")
mag_drs <- read.csv("./csv/mag_drs.csv") %>% mutate(phenomena = "Luftdruck")


#wies_temp <- get_stat_measurements(Wiesbaden, temps)
#write.csv(wies_temp, "./csv/wies_t.csv")
#wies_humi <- get_stat_measurements(Wiesbaden, feuchte)
#write.csv(wies_humi, "./csv/wies_h.csv")
wies_temp <- read.csv("./csv/wies_t.csv") %>% mutate(phenomena = "Temperatur")
wies_humi <- read.csv("./csv/wies_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
wies_th <- bind_rows(wies_temp, wies_humi) %>% group_by(phenomena)
#wies_temp <- get_stat_measurements(Wiesbaden, PM10)
#wies_humi <- get_stat_measurements(Wiesbaden, PM25)
wies_pm10 <- read.csv("./csv/wies_10.csv") %>% mutate(phenomena = "PM10")
wies_pm25 <- read.csv("./csv/wies_25.csv") %>% mutate(phenomena = "PM25")
wies_pm <- bind_rows(wies_pm10, wies_pm25) %>% group_by(phenomena)
#wies_dr <- get_stat_measurements(Wiesbaden, Luftdruck)
#write.csv(wies_dr, "./csv/wies_dr.csv")
#wies_dr <- read.csv("./csv/wies_dr.csv") %>% mutate(phenomena = "Luftdruck")

#wies_temps <- get_stat_measurements_si(Wiesbaden, temps)
#write.csv(wies_temps, "./csv/wies_ts.csv")
#wies_humis <- get_stat_measurements_si(Wiesbaden, feuchte)
#write.csv(wies_humis, "./csv/wies_hs.csv")
wies_temps <- read.csv("./csv/wies_ts.csv") %>% mutate(phenomena = "Temperatur")
wies_humis <- read.csv("./csv/wies_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
wies_ths <- bind_rows(wies_temps, wies_humis) %>% group_by(phenomena)
#wies_temps <- get_stat_measurements_si(Wiesbaden, PM10)
#wies_humis <- get_stat_measurements_si(Wiesbaden, PM25)
wies_pm10s <- read.csv("./csv/wies_10.csv") %>% mutate(phenomena = "PM10")
wies_pm25s <- read.csv("./csv/wies_25.csv") %>% mutate(phenomena = "PM25")
wies_pms <- bind_rows(wies_pm10, wies_pm25) %>% group_by(phenomena)
#wies_drs <- get_stat_measurements_si(Wiesbaden, Luftdruck)
#write.csv(wies_drs, "./csv/wies_drs.csv")
#wies_drs <- read.csv("./csv/wies_drs.csv") %>% mutate(phenomena = "Luftdruck")


#mai_temp <- get_stat_measurements(Mainz, temps)
#write.csv(mai_temp, "./csv/mai_t.csv")
#mai_humi <- get_stat_measurements(Mainz, feuchte)
#write.csv(mai_humi, "./csv/mai_h.csv")
mai_temp <- read.csv("./csv/mai_t.csv") %>% mutate(phenomena = "Temperatur")
mai_humi <- read.csv("./csv/mai_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
mai_th <- bind_rows(mai_temp, mai_humi) %>% group_by(phenomena)
#mai_temp <- get_stat_measurements(Mainz, PM10)
#mai_humi <- get_stat_measurements(Mainz, PM25)
mai_pm10 <- read.csv("./csv/mai_10.csv") %>% mutate(phenomena = "PM10")
mai_pm25 <- read.csv("./csv/mai_25.csv") %>% mutate(phenomena = "PM25")
mai_pm <- bind_rows(mai_pm10, mai_pm25) %>% group_by(phenomena)
#mai_dr <- get_stat_measurements(Mainz, Luftdruck)
#write.csv(mai_dr, "./csv/mai_dr.csv")
#mai_dr <- read.csv("./csv/mai_dr.csv") %>% mutate(phenomena = "Luftdruck")

#mai_temps <- get_stat_measurements_si(Mainz, temps)
#write.csv(mai_temps, "./csv/mai_ts.csv")
#mai_humis <- get_stat_measurements_si(Mainz, feuchte)
#write.csv(mai_humis, "./csv/mai_hs.csv")
mai_temps <- read.csv("./csv/mai_ts.csv") %>% mutate(phenomena = "Temperatur")
mai_humis <- read.csv("./csv/mai_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
mai_ths <- bind_rows(mai_temps, mai_humis) %>% group_by(phenomena)
#mai_temps <- get_stat_measurements_si(Mainz, PM10)
#mai_humis <- get_stat_measurements_si(Mainz, PM25)
mai_pm10s <- read.csv("./csv/mai_10.csv") %>% mutate(phenomena = "PM10")
mai_pm25s <- read.csv("./csv/mai_25.csv") %>% mutate(phenomena = "PM25")
mai_pms <- bind_rows(mai_pm10, mai_pm25) %>% group_by(phenomena)
#mai_drs <- get_stat_measurements_si(Mainz, Luftdruck)
#write.csv(mai_drs, "./csv/mai_drs.csv")
#mai_drs <- read.csv("./csv/mai_drs.csv") %>% mutate(phenomena = "Luftdruck")



#kr_temp <- get_stat_measurements(Karlsruhe, temps)
#write.csv(kr_temp, "./csv/kr_t.csv")
#kr_humi <- get_stat_measurements(Karlsruhe, feuchte)
#write.csv(kr_humi, "./csv/kr_h.csv")
kr_temp <- read.csv("./csv/kr_t.csv") %>% mutate(phenomena = "Temperatur")
kr_humi <- read.csv("./csv/kr_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
kr_th <- bind_rows(kr_temp, kr_humi) %>% group_by(phenomena)
#kr_temp <- get_stat_measurements(Karlsruhe, PM10)
#kr_humi <- get_stat_measurements(Karlsruhe, PM25)
kr_pm10 <- read.csv("./csv/kr_10.csv") %>% mutate(phenomena = "PM10")
kr_pm25 <- read.csv("./csv/kr_25.csv") %>% mutate(phenomena = "PM25")
kr_pm <- bind_rows(kr_pm10, kr_pm25) %>% group_by(phenomena)
#kr_dr <- get_stat_measurements(Karlsruhe, Luftdruck)
#write.csv(kr_dr, "./csv/kr_dr.csv")
kr_dr <- read.csv("./csv/kr_dr.csv") %>% mutate(phenomena = "Luftdruck")

#kr_temps <- get_stat_measurements_si(Karlsruhe, temps)
#write.csv(kr_temps, "./csv/kr_ts.csv")
#kr_humis <- get_stat_measurements_si(Karlsruhe, feuchte)
#write.csv(kr_humis, "./csv/kr_hs.csv")
kr_temps <- read.csv("./csv/kr_ts.csv") %>% mutate(phenomena = "Temperatur")
kr_humis <- read.csv("./csv/kr_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
kr_ths <- bind_rows(kr_temps, kr_humis) %>% group_by(phenomena)
#kr_temps <- get_stat_measurements_si(Karlsruhe, PM10)
#kr_humis <- get_stat_measurements_si(Karlsruhe, PM25)
kr_pm10s <- read.csv("./csv/kr_10.csv") %>% mutate(phenomena = "PM10")
kr_pm25s <- read.csv("./csv/kr_25.csv") %>% mutate(phenomena = "PM25")
kr_pms <- bind_rows(kr_pm10, kr_pm25) %>% group_by(phenomena)
#kr_drs <- get_stat_measurements_si(Karlsruhe, Luftdruck)
#write.csv(kr_drs, "./csv/kr_drs.csv")
kr_drs <- read.csv("./csv/kr_drs.csv") %>% mutate(phenomena = "Luftdruck")


#sw_temp <- get_stat_measurements(Schwerin, temps)
#write.csv(sw_temp, "./csv/sw_t.csv")
#sw_humi <- get_stat_measurements(Schwerin, feuchte)
#write.csv(sw_humi, "./csv/sw_h.csv")
sw_temp <- read.csv("./csv/sw_t.csv") %>% mutate(phenomena = "Temperatur")
sw_humi <- read.csv("./csv/sw_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
sw_th <- bind_rows(sw_temp, sw_humi) %>% group_by(phenomena)
#sw_temp <- get_stat_measurements(Schwerin, PM10)
#sw_humi <- get_stat_measurements(Schwerin, PM25)
sw_pm10 <- read.csv("./csv/sw_10.csv") %>% mutate(phenomena = "PM10")
sw_pm25 <- read.csv("./csv/sw_25.csv") %>% mutate(phenomena = "PM25")
sw_pm <- bind_rows(sw_pm10, sw_pm25) %>% group_by(phenomena)
#sw_dr <- get_stat_measurements(Schwerin, Luftdruck)
#write.csv(sw_dr, "./csv/sw_dr.csv")
sw_dr <- read.csv("./csv/sw_dr.csv") %>% mutate(phenomena = "Luftdruck")

#sw_temps <- get_stat_measurements_si(Schwerin, temps)
#write.csv(sw_temps, "./csv/sw_ts.csv")
#sw_humis <- get_stat_measurements_si(Schwerin, feuchte)
#write.csv(sw_humis, "./csv/sw_hs.csv")
sw_temps <- read.csv("./csv/sw_ts.csv") %>% mutate(phenomena = "Temperatur")
sw_humis <- read.csv("./csv/sw_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
sw_ths <- bind_rows(sw_temps, sw_humis) %>% group_by(phenomena)
#sw_temps <- get_stat_measurements_si(Schwerin, PM10)
#sw_humis <- get_stat_measurements_si(Schwerin, PM25)
sw_pm10s <- read.csv("./csv/sw_10.csv") %>% mutate(phenomena = "PM10")
sw_pm25s <- read.csv("./csv/sw_25.csv") %>% mutate(phenomena = "PM25")
sw_pms <- bind_rows(sw_pm10, sw_pm25) %>% group_by(phenomena)
#sw_drs <- get_stat_measurements_si(Schwerin, Luftdruck)
#write.csv(sw_drs, "./csv/sw_drs.csv")
sw_drs <- read.csv("./csv/sw_drs.csv") %>% mutate(phenomena = "Luftdruck")


#rb_temp <- get_stat_measurements(Regensburg, temps)
#write.csv(rb_temp, "./csv/rb_t.csv")
#rb_humi <- get_stat_measurements(Regensburg, feuchte)
#write.csv(rb_humi, "./csv/rb_h.csv")
rb_temp <- read.csv("./csv/rb_t.csv") %>% mutate(phenomena = "Temperatur")
rb_humi <- read.csv("./csv/rb_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
rb_th <- bind_rows(rb_temp, rb_humi) %>% group_by(phenomena)
#rb_temp <- get_stat_measurements(Regensburg, PM10)
#rb_humi <- get_stat_measurements(Regensburg, PM25)
rb_pm10 <- read.csv("./csv/rb_10.csv") %>% mutate(phenomena = "PM10")
rb_pm25 <- read.csv("./csv/rb_25.csv") %>% mutate(phenomena = "PM25")
rb_pm <- bind_rows(rb_pm10, rb_pm25) %>% group_by(phenomena)
#rb_dr <- get_stat_measurements(Regensburg, Luftdruck)
#write.csv(rb_dr, "./csv/rb_dr.csv")
#rb_dr <- read.csv("./csv/rb_dr.csv") %>% mutate(phenomena = "Luftdruck")

#rb_temps <- get_stat_measurements_si(Regensburg, temps)
#write.csv(rb_temps, "./csv/rb_ts.csv")
#rb_humis <- get_stat_measurements_si(Regensburg, feuchte)
#write.csv(rb_humis, "./csv/rb_hs.csv")
rb_temps <- read.csv("./csv/rb_ts.csv") %>% mutate(phenomena = "Temperatur")
rb_humis <- read.csv("./csv/rb_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
rb_ths <- bind_rows(rb_temps, rb_humis) %>% group_by(phenomena)
#rb_temps <- get_stat_measurements_si(Regensburg, PM10)
#rb_humis <- get_stat_measurements_si(Regensburg, PM25)
rb_pm10s <- read.csv("./csv/rb_10.csv") %>% mutate(phenomena = "PM10")
rb_pm25s <- read.csv("./csv/rb_25.csv") %>% mutate(phenomena = "PM25")
rb_pms <- bind_rows(rb_pm10, rb_pm25) %>% group_by(phenomena)
#rb_drs <- get_stat_measurements_si(Regensburg, Luftdruck)
#write.csv(rb_drs, "./csv/rb_drs.csv")
#rb_drs <- read.csv("./csv/rb_drs.csv") %>% mutate(phenomena = "Luftdruck")



#fl_temp <- get_stat_measurements(Flensburg, temps)
#write.csv(fl_temp, "./csv/fl_t.csv")
#fl_humi <- get_stat_measurements(Flensburg, feuchte)
#write.csv(fl_humi, "./csv/fl_h.csv")
fl_temp <- read.csv("./csv/fl_t.csv") %>% mutate(phenomena = "Temperatur")
fl_humi <- read.csv("./csv/fl_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
fl_th <- bind_rows(fl_temp, fl_humi) %>% group_by(phenomena)
#fl_temp <- get_stat_measurements(Flensburg, PM10)
#fl_humi <- get_stat_measurements(Flensburg, PM25)
fl_pm10 <- read.csv("./csv/fl_10.csv") %>% mutate(phenomena = "PM10")
fl_pm25 <- read.csv("./csv/fl_25.csv") %>% mutate(phenomena = "PM25")
fl_pm <- bind_rows(fl_pm10, fl_pm25) %>% group_by(phenomena)
#fl_dr <- get_stat_measurements(Flensburg, Luftdruck)
#write.csv(fl_dr, "./csv/fl_dr.csv")
fl_dr <- read.csv("./csv/fl_dr.csv") %>% mutate(phenomena = "Luftdruck")

#fl_temps <- get_stat_measurements_si(Flensburg, temps)
#write.csv(fl_temps, "./csv/fl_ts.csv")
#fl_humis <- get_stat_measurements_si(Flensburg, feuchte)
#write.csv(fl_humis, "./csv/fl_hs.csv")
fl_temps <- read.csv("./csv/fl_ts.csv") %>% mutate(phenomena = "Temperatur")
fl_humis <- read.csv("./csv/fl_hs.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
fl_ths <- bind_rows(fl_temps, fl_humis) %>% group_by(phenomena)
#fl_temps <- get_stat_measurements_si(Flensburg, PM10)
#fl_humis <- get_stat_measurements_si(Flensburg, PM25)
fl_pm10s <- read.csv("./csv/fl_10.csv") %>% mutate(phenomena = "PM10")
fl_pm25s <- read.csv("./csv/fl_25.csv") %>% mutate(phenomena = "PM25")
fl_pms <- bind_rows(fl_pm10, fl_pm25) %>% group_by(phenomena)
#fl_drs <- get_stat_measurements_si(Flensburg, Luftdruck)
#write.csv(fl_drs, "./csv/fl_drs.csv")
fl_drs <- read.csv("./csv/fl_drs.csv") %>% mutate(phenomena = "Luftdruck")



#dd_temp <- get_stat_measurements(Duesseldorf, temps)
#write.csv(dd_temp, "./csv/dd_t.csv")
#dd_humi <- get_stat_measurements(Duesseldorf, feuchte)
#write.csv(dd_humi, "./csv/dd_h.csv")
dd_temp <- read.csv("./csv/dd_t.csv") %>% mutate(phenomena = "Temperatur")
dd_humi <- read.csv("./csv/dd_h.csv") %>% mutate(phenomena = "Luftfeuchtigkeit")
dd_th <- bind_rows(dd_temp, dd_humi) %>% group_by(phenomena)
#dd_temp <- get_stat_measurements(Duesseldorf, PM10)
#dd_humi <- get_stat_measurements(Duesseldorf, PM25)
dd_pm10 <- read.csv("./csv/dd_10.csv") %>% mutate(phenomena = "PM10")
dd_pm25 <- read.csv("./csv/dd_25.csv") %>% mutate(phenomena = "PM25")
dd_pm <- bind_rows(dd_pm10, dd_pm25) %>% group_by(phenomena)
#dd_dr <- get_stat_measurements(Duesseldorf, Luftdruck)
#write.csv(dd_dr, "./csv/dd_dr.csv")
#dd_dr <- read.csv("./csv/dd_dr.csv") %>% mutate(phenomena = "Luftdruck")



#Munch_pm10 <- get_stat_measurements(München, PM10)
#write.csv(Munch_pm10, "./csv/munch_pm10.csv")
#Munch_pm25 <- get_stat_measurements(München, PM25)
#write.csv(Munch_pm25, "./csv/munch_pm25.csv")
Munch_pm10 <- read.csv("./csv/munch_10.csv") %>% mutate(phenomena = "PM10")
Munch_pm25 <- read.csv("./csv/munch_25.csv") %>% mutate(phenomena = "PM25")
Munch_pm <- bind_rows(Munch_pm10, Munch_pm25) %>% group_by(phenomena)

#Munch_pm10s <- get_stat_measurements_si(München, PM10)
#write.csv(Munch_pm10s, "./csv/munch_pm10s.csv")
#Munch_pm25s <- get_stat_measurements_si(München, PM25)
#write.csv(Munch_pm25s, "./csv/munch_pm25s.csv")
Munch_pm10s <- read.csv("./csv/munch_pm10s.csv") %>% mutate(phenomena = "PM10")
Munch_pm25s <- read.csv("./csv/munch_pm25s.csv") %>% mutate(phenomena = "PM25")
Munch_pms <- bind_rows(Munch_pm10s, Munch_pm25s) %>% group_by(phenomena)


#ham_pm10 <- get_stat_measurements(Hamburg, PM10)
#write.csv(ham_pm10, "./csv/ham_pm10.csv")
#ham_pm25 <- get_stat_measurements(Hamburg, PM25)
#write.csv(ham_pm25, "./csv/ham_pm25.csv")
ham_pm10 <- read.csv("./csv/ham_10.csv") %>% mutate(phenomena = "PM10")
ham_pm25 <- read.csv("./csv/ham_25.csv") %>% mutate(phenomena = "PM25")
ham_pm <- bind_rows(ham_pm10, ham_pm25) %>% group_by(phenomena)

#ham_pm10s <- get_stat_measurements_si(Hamburg, PM10)
#write.csv(ham_pm10s, "./csv/ham_pm10s.csv")
#ham_pm25s <- get_stat_measurements_si(Hamburg, PM25)
#write.csv(ham_pm25s, "./csv/ham_pm25s.csv")
ham_pm10s <- read.csv("./csv/ham_pm10s.csv") %>% mutate(phenomena = "PM10")
ham_pm25s <- read.csv("./csv/ham_pm25s.csv") %>% mutate(phenomena = "PM25")
ham_pms <- bind_rows(ham_pm10s, ham_pm25s) %>% group_by(phenomena)

#han_pm10 <- get_stat_measurements(Hannover, PM10)
#write.csv(han_pm10, "./csv/han_pm10.csv")
#han_pm25 <- get_stat_measurements(Hannover, PM25)
#write.csv(han_pm25, "./csv/han_pm25.csv")
han_pm10 <- read.csv("./csv/han_10.csv") %>% mutate(phenomena = "PM10")
han_pm25 <- read.csv("./csv/han_25.csv") %>% mutate(phenomena = "PM25")
han_pm <- bind_rows(han_pm10, han_pm25) %>% group_by(phenomena)

#han_pm10s <- get_stat_measurements_si(Hannover, PM10)
#write.csv(han_pm10s, "./csv/han_pm10s.csv")
#han_pm25s <- get_stat_measurements_si(Hannover, PM25)
#write.csv(han_pm25s, "./csv/han_pm25s.csv")
han_pm10s <- read.csv("./csv/han_pm10s.csv") %>% mutate(phenomena = "PM10")
han_pm25s <- read.csv("./csv/han_pm25s.csv") %>% mutate(phenomena = "PM25")
han_pms <- bind_rows(han_pm10s, han_pm25s) %>% group_by(phenomena)


#fra_pm10 <- get_stat_measurements(Frankfurt, PM10)
#write.csv(fra_pm10, "./csv/fra_pm10.csv")
#fra_pm25 <- get_stat_measurements(Frankfurt, PM25)
#write.csv(fra_pm25, "./csv/fra_pm25.csv")
fra_pm10 <- read.csv("./csv/fra_10.csv") %>% mutate(phenomena = "PM10")
fra_pm25 <- read.csv("./csv/fra_25.csv") %>% mutate(phenomena = "PM25")
fra_pm <- bind_rows(fra_pm10, fra_pm25) %>% group_by(phenomena)

#fra_pm10s <- get_stat_measurements_si(Frankfurt, PM10)
#write.csv(fra_pm10s, "./csv/fra_pm10s.csv")
#fra_pm25s <- get_stat_measurements_si(Frankfurt, PM25)
#write.csv(fra_pm25s, "./csv/fra_pm25s.csv")
fra_pm10s <- read.csv("./csv/fra_pm10s.csv") %>% mutate(phenomena = "PM10")
fra_pm25s <- read.csv("./csv/fra_pm25s.csv") %>% mutate(phenomena = "PM25")
fra_pms <- bind_rows(fra_pm10s, fra_pm25s) %>% group_by(phenomena)



#muns_pm10 <- get_stat_measurements(Münster, PM10)
#write.csv(muns_pm10, "./csv/muns_pm10.csv")
#muns_pm25 <- get_stat_measurements(Münster, PM25)
#write.csv(muns_pm25, "./csv/muns_pm25.csv")
muns_pm10 <- read.csv("./csv/muns_10.csv") %>% mutate(phenomena = "PM10")
muns_pm25 <- read.csv("./csv/muns_25.csv") %>% mutate(phenomena = "PM25")
muns_pm <- bind_rows(muns_pm10, muns_pm25) %>% group_by(phenomena)

#muns_pm10s <- get_stat_measurements_si(Münster, PM10)
#write.csv(muns_pm10s, "./csv/muns_pm10s.csv")
#muns_pm25s <- get_stat_measurements_si(Münster, PM25)
#write.csv(muns_pm25s, "./csv/muns_pm25s.csv")
muns_pm10s <- read.csv("./csv/muns_pm10s.csv") %>% mutate(phenomena = "PM10")
muns_pm25s <- read.csv("./csv/muns_pm25s.csv") %>% mutate(phenomena = "PM25")
muns_pms <- bind_rows(muns_pm10s, muns_pm25s) %>% group_by(phenomena)

#ber_pm10 <- get_stat_measurements(Berlin, PM10)
#write.csv(ber_pm10, "./csv/ber_pm10.csv")
#ber_pm25 <- get_stat_measurements(Berlin, PM25)
#write.csv(ber_pm25, "./csv/ber_pm25.csv")
ber_pm10 <- read.csv("./csv/ber_10.csv") %>% mutate(phenomena = "PM10")
ber_pm25 <- read.csv("./csv/ber_25.csv") %>% mutate(phenomena = "PM25")
ber_pm <- bind_rows(ber_pm10, ber_pm25) %>% group_by(phenomena)

#ber_pm10s <- get_stat_measurements_si(Berlin, PM10)
#write.csv(ber_pm10s, "./csv/ber_pm10s.csv")
#ber_pm25s <- get_stat_measurements_si(Berlin, PM25)
#write.csv(ber_pm25s, "./csv/ber_pm25s.csv")
ber_pm10s <- read.csv("./csv/ber_pm10s.csv") %>% mutate(phenomena = "PM10")
ber_pm25s <- read.csv("./csv/ber_pm25s.csv") %>% mutate(phenomena = "PM25")
ber_pms <- bind_rows(ber_pm10s, ber_pm25s) %>% group_by(phenomena)



#kol_pm10 <- get_stat_measurements(Köln, PM10)
#write.csv(kol_pm10, "./csv/kol_pm10.csv")
#kol_pm25 <- get_stat_measurements(Köln, PM25)
#write.csv(kol_pm25, "./csv/kol_pm25.csv")
kol_pm10 <- read.csv("./csv/kol_10.csv") %>% mutate(phenomena = "PM10")
kol_pm25 <- read.csv("./csv/kol_25.csv") %>% mutate(phenomena = "PM25")
kol_pm <- bind_rows(kol_pm10, kol_pm25) %>% group_by(phenomena)

#kol_pm10s <- get_stat_measurements_si(Köln, PM10)
#write.csv(kol_pm10s, "./csv/kol_pm10s.csv")
#kol_pm25s <- get_stat_measurements_si(Köln, PM25)
#write.csv(kol_pm25s, "./csv/kol_pm25s.csv")
kol_pm10s <- read.csv("./csv/kol_pm10s.csv") %>% mutate(phenomena = "PM10")
kol_pm25s <- read.csv("./csv/kol_pm25s.csv") %>% mutate(phenomena = "PM25")
kol_pms <- bind_rows(kol_pm10s, kol_pm25s) %>% group_by(phenomena)


#stu_pm10 <- get_stat_measurements(Stuttgart, PM10)
#write.csv(stu_pm10, "./csv/stu_pm10.csv")
#stu_pm25 <- get_stat_measurements(Stuttgart, PM25)
#write.csv(stu_pm25, "./csv/stu_pm25.csv")
stu_pm10 <- read.csv("./csv/stu_10.csv") %>% mutate(phenomena = "PM10")
stu_pm25 <- read.csv("./csv/stu_25.csv") %>% mutate(phenomena = "PM25")
stu_pm <- bind_rows(stu_pm10, stu_pm25) %>% group_by(phenomena)

#stu_pm10s <- get_stat_measurements_si(Stuttgart, PM10)
#write.csv(stu_pm10s, "./csv/stu_pm10s.csv")
#stu_pm25s <- get_stat_measurements_si(Stuttgart, PM25)
#write.csv(stu_pm25s, "./csv/stu_pm25s.csv")
stu_pm10s <- read.csv("./csv/stu_pm10s.csv") %>% mutate(phenomena = "PM10")
stu_pm25s <- read.csv("./csv/stu_pm25s.csv") %>% mutate(phenomena = "PM25")
stu_pms <- bind_rows(stu_pm10s, stu_pm25s) %>% group_by(phenomena)




#klt_pm10 <- get_stat_measurements(Kaiserslauternt, PM10)
#write.csv(klt_pm10, "./csv/klt_pm10.csv")
#klt_pm25 <- get_stat_measurements(Kaiserslauternt, PM25)
#write.csv(klt_pm25, "./csv/klt_pm25.csv")
klt_pm10 <- read.csv("./csv/klt_10.csv") %>% mutate(phenomena = "PM10")
klt_pm25 <- read.csv("./csv/klt_25.csv") %>% mutate(phenomena = "PM25")
klt_pm <- bind_rows(klt_pm10, klt_pm25) %>% group_by(phenomena)

#klt_pm10s <- get_stat_measurements_si(Kaiserslauternt, PM10)
##write.csv(klt_pm10s, "./csv/klt_pm10s.csv")
#klt_pm25s <- get_stat_measurements_si(Kaiserslauternt, PM25)
#wrte.csv(klt_pm25s, "./csv/klt_pm25s.csv")
klt_pm10s <- read.csv("./csv/klt_pm10s.csv") %>% mutate(phenomena = "PM10")
klt_pm25s <- read.csv("./csv/klt_pm25s.csv") %>% mutate(phenomena = "PM25")
klt_pms <- bind_rows(klt_pm10s, klt_pm25s) %>% group_by(phenomena)



#old_pm10 <- get_stat_measurements(Oldenburg, PM10)
#write.csv(old_pm10, "./csv/old_pm10.csv")
#old_pm25 <- get_stat_measurements(Oldenburg, PM25)
#write.csv(old_pm25, "./csv/old_pm25.csv")
old_pm10 <- read.csv("./csv/old_10.csv") %>% mutate(phenomena = "PM10")
old_pm25 <- read.csv("./csv/old_25.csv") %>% mutate(phenomena = "PM25")
old_pm <- bind_rows(old_pm10, old_pm25) %>% group_by(phenomena)

#old_pm10s <- get_stat_measurements_si(Oldenburg, PM10)
#write.csv(old_pm10s, "./csv/old_pm10s.csv")
#old_pm25s <- get_stat_measurements_si(Oldenburg, PM25)
#write.csv(old_pm25s, "./csv/old_pm25s.csv")
old_pm10s <- read.csv("./csv/old_pm10s.csv") %>% mutate(phenomena = "PM10")
old_pm25s <- read.csv("./csv/old_pm25s.csv") %>% mutate(phenomena = "PM25")
old_pms <- bind_rows(old_pm10s, old_pm25s) %>% group_by(phenomena)



#lpz_pm10 <- get_stat_measurements(Leipzig, PM10)
#write.csv(lpz_pm10, "./csv/lpz_pm10.csv")
#lpz_pm25 <- get_stat_measurements(Leipzig, PM25)
#write.csv(lpz_pm25, "./csv/lpz_pm25.csv")
lpz_pm10 <- read.csv("./csv/lpz_10.csv") %>% mutate(phenomena = "PM10")
lpz_pm25 <- read.csv("./csv/lpz_25.csv") %>% mutate(phenomena = "PM25")
lpz_pm <- bind_rows(lpz_pm10, lpz_pm25) %>% group_by(phenomena)

#lpz_pm10s <- get_stat_measurements_si(Leipzig, PM10)
#write.csv(lpz_pm10s, "./csv/lpz_pm10s.csv")
#lpz_pm25s <- get_stat_measurements_si(Leipzig, PM25)
#write.csv(lpz_pm25s, "./csv/lpz_pm25s.csv")
lpz_pm10s <- read.csv("./csv/lpz_pm10s.csv") %>% mutate(phenomena = "PM10")
lpz_pm25s <- read.csv("./csv/lpz_pm25s.csv") %>% mutate(phenomena = "PM25")
lpz_pms <- bind_rows(lpz_pm10s, lpz_pm25s) %>% group_by(phenomena)


#ros_pm10 <- get_stat_measurements(Rostock, PM10)
#write.csv(ros_pm10, "./csv/ros_pm10.csv")
#ros_pm25 <- get_stat_measurements(Rostock, PM25)
#write.csv(ros_pm25, "./csv/ros_pm25.csv")
ros_pm10 <- read.csv("./csv/ros_10.csv") %>% mutate(phenomena = "PM10")
ros_pm25 <- read.csv("./csv/ros_25.csv") %>% mutate(phenomena = "PM25")
ros_pm <- bind_rows(ros_pm10, ros_pm25) %>% group_by(phenomena)

#ros_pm10s <- get_stat_measurements_si(Rostock, PM10)
#write.csv(ros_pm10s, "./csv/ros_pm10s.csv")
#ros_pm25s <- get_stat_measurements_si(Rostock, PM25)
#write.csv(ros_pm25s, "./csv/ros_pm25s.csv")
ros_pm10s <- read.csv("./csv/ros_pm10s.csv") %>% mutate(phenomena = "PM10")
ros_pm25s <- read.csv("./csv/ros_pm25s.csv") %>% mutate(phenomena = "PM25")
ros_pms <- bind_rows(ros_pm10s, ros_pm25s) %>% group_by(phenomena)


#sar_pm10 <- get_stat_measurements(Saarbruecken, PM10)
#write.csv(sar_pm10, "./csv/sar_pm10.csv")
#sar_pm25 <- get_stat_measurements(Saarbruecken, PM25)
#write.csv(sar_pm25, "./csv/sar_pm25.csv")
sar_pm10 <- read.csv("./csv/sar_10.csv") %>% mutate(phenomena = "PM10")
sar_pm25 <- read.csv("./csv/sar_25.csv") %>% mutate(phenomena = "PM25")
sar_pm <- bind_rows(sar_pm10, sar_pm25) %>% group_by(phenomena)

#sar_pm10s <- get_stat_measurements_si(Saarbruecken, PM10)
#write.csv(sar_pm10s, "./csv/sar_pm10s.csv")
#sar_pm25s <- get_stat_measurements_si(Saarbruecken, PM25)
#write.csv(sar_pm25s, "./csv/sar_pm25s.csv")
sar_pm10s <- read.csv("./csv/sar_pm10s.csv") %>% mutate(phenomena = "PM10")
sar_pm25s <- read.csv("./csv/sar_pm25s.csv") %>% mutate(phenomena = "PM25")
sar_pms <- bind_rows(sar_pm10s, sar_pm25s) %>% group_by(phenomena)


#sar_pm10 <- get_stat_measurements(Chemnitz, PM10)
#write.csv(sar_pm10, "./csv/sar_pm10.csv")
#sar_pm25 <- get_stat_measurements(Chemnitz, PM25)
#write.csv(sar_pm25, "./csv/sar_pm25.csv")
sar_pm10 <- read.csv("./csv/sar_10.csv") %>% mutate(phenomena = "PM10")
sar_pm25 <- read.csv("./csv/sar_25.csv") %>% mutate(phenomena = "PM25")
sar_pm <- bind_rows(sar_pm10, sar_pm25) %>% group_by(phenomena)

#sar_pm10s <- get_stat_measurements_si(Chemnitz, PM10)
#write.csv(sar_pm10s, "./csv/sar_pm10s.csv")
#sar_pm25s <- get_stat_measurements_si(Chemnitz, PM25)
#write.csv(sar_pm25s, "./csv/sar_pm25s.csv")
sar_pm10s <- read.csv("./csv/sar_pm10s.csv") %>% mutate(phenomena = "PM10")
sar_pm25s <- read.csv("./csv/sar_pm25s.csv") %>% mutate(phenomena = "PM25")
sar_pms <- bind_rows(sar_pm10s, sar_pm25s) %>% group_by(phenomena)


#kl_pm10 <- get_stat_measurements(Kiel, PM10)
#write.csv(kl_pm10, "./csv/kl_pm10.csv")
#kl_pm25 <- get_stat_measurements(Kiel, PM25)
#write.csv(kl_pm25, "./csv/kl_pm25.csv")
kl_pm10 <- read.csv("./csv/kl_10.csv") %>% mutate(phenomena = "PM10")
kl_pm25 <- read.csv("./csv/kl_25.csv") %>% mutate(phenomena = "PM25")
kl_pm <- bind_rows(kl_pm10, kl_pm25) %>% group_by(phenomena)

#kl_pm10s <- get_stat_measurements_si(Kiel, PM10)
#write.csv(kl_pm10s, "./csv/kl_pm10s.csv")
#kl_pm25s <- get_stat_measurements_si(Kiel, PM25)
#write.csv(kl_pm25s, "./csv/kl_pm25s.csv")
kl_pm10s <- read.csv("./csv/kl_pm10s.csv") %>% mutate(phenomena = "PM10")
kl_pm25s <- read.csv("./csv/kl_pm25s.csv") %>% mutate(phenomena = "PM25")
kl_pms <- bind_rows(kl_pm10s, kl_pm25s) %>% group_by(phenomena)


#osna_pm10 <- get_stat_measurements(Osnabrück, PM10)
#write.csv(osna_pm10, "./csv/osna_pm10.csv")
#osna_pm25 <- get_stat_measurements(Osnabrück, PM25)
#write.csv(osna_pm25, "./csv/osna_pm25.csv")
osna_pm10 <- read.csv("./csv/osna_10.csv") %>% mutate(phenomena = "PM10")
osna_pm25 <- read.csv("./csv/osna_25.csv") %>% mutate(phenomena = "PM25")
osna_pm <- bind_rows(osna_pm10, osna_pm25) %>% group_by(phenomena)

#osna_pm10s <- get_stat_measurements_si(Osnabrück, PM10)
#write.csv(osna_pm10s, "./csv/osna_pm10s.csv")
#osna_pm25s <- get_stat_measurements_si(Osnabrück, PM25)
#write.csv(osna_pm25s, "./csv/osna_pm25s.csv")
osna_pm10s <- read.csv("./csv/osna_pm10s.csv") %>% mutate(phenomena = "PM10")
osna_pm25s <- read.csv("./csv/osna_pm25s.csv") %>% mutate(phenomena = "PM25")
osna_pms <- bind_rows(osna_pm10s, osna_pm25s) %>% group_by(phenomena)



#mag_pm10 <- get_stat_measurements(Magdeburg, PM10)
#write.csv(mag_pm10, "./csv/mag_pm10.csv")
#mag_pm25 <- get_stat_measurements(Magdeburg, PM25)
#write.csv(mag_pm25, "./csv/mag_pm25.csv")
mag_pm10 <- read.csv("./csv/mag_10.csv") %>% mutate(phenomena = "PM10")
mag_pm25 <- read.csv("./csv/mag_25.csv") %>% mutate(phenomena = "PM25")
mag_pm <- bind_rows(mag_pm10, mag_pm25) %>% group_by(phenomena)

#mag_pm10s <- get_stat_measurements_si(Magdeburg, PM10)
#write.csv(mag_pm10s, "./csv/mag_pm10s.csv")
#mag_pm25s <- get_stat_measurements_si(Magdeburg, PM25)
#write.csv(mag_pm25s, "./csv/mag_pm25s.csv")
mag_pm10s <- read.csv("./csv/mag_pm10s.csv") %>% mutate(phenomena = "PM10")
mag_pm25s <- read.csv("./csv/mag_pm25s.csv") %>% mutate(phenomena = "PM25")
mag_pms <- bind_rows(mag_pm10s, mag_pm25s) %>% group_by(phenomena)


#wies_pm10 <- get_stat_measurements(Wiesbaden, PM10)
#write.csv(wies_pm10, "./csv/wies_pm10.csv")
#wies_pm25 <- get_stat_measurements(Wiesbaden, PM25)
#write.csv(wies_pm25, "./csv/wies_pm25.csv")
wies_pm10 <- read.csv("./csv/wies_10.csv") %>% mutate(phenomena = "PM10")
wies_pm25 <- read.csv("./csv/wies_25.csv") %>% mutate(phenomena = "PM25")
wies_pm <- bind_rows(wies_pm10, wies_pm25) %>% group_by(phenomena)

#wies_pm10s <- get_stat_measurements_si(Wiesbaden, PM10)
#write.csv(wies_pm10s, "./csv/wies_pm10s.csv")
#wies_pm25s <- get_stat_measurements_si(Wiesbaden, PM25)
#write.csv(wies_pm25s, "./csv/wies_pm25s.csv")
wies_pm10s <- read.csv("./csv/wies_pm10s.csv") %>% mutate(phenomena = "PM10")
wies_pm25s <- read.csv("./csv/wies_pm25s.csv") %>% mutate(phenomena = "PM25")
wies_pms <- bind_rows(wies_pm10s, wies_pm25s) %>% group_by(phenomena)



#mai_pm10 <- get_stat_measurements(Mainz, PM10)
#write.csv(mai_pm10, "./csv/mai_pm10.csv")
#mai_pm25 <- get_stat_measurements(Mainz, PM25)
#write.csv(mai_pm25, "./csv/mai_pm25.csv")
mai_pm10 <- read.csv("./csv/mai_10.csv") %>% mutate(phenomena = "PM10")
mai_pm25 <- read.csv("./csv/mai_25.csv") %>% mutate(phenomena = "PM25")
mai_pm <- bind_rows(mai_pm10, mai_pm25) %>% group_by(phenomena)

#mai_pm10s <- get_stat_measurements_si(Mainz, PM10)
#write.csv(mai_pm10s, "./csv/mai_pm10s.csv")
#mai_pm25s <- get_stat_measurements_si(Mainz, PM25)
#write.csv(mai_pm25s, "./csv/mai_pm25s.csv")
mai_pm10s <- read.csv("./csv/mai_pm10s.csv") %>% mutate(phenomena = "PM10")
mai_pm25s <- read.csv("./csv/mai_pm25s.csv") %>% mutate(phenomena = "PM25")
mai_pms <- bind_rows(mai_pm10s, mai_pm25s) %>% group_by(phenomena)


#kr_pm10 <- get_stat_measurements(Karlsruhe, PM10)
#write.csv(kr_pm10, "./csv/kr_pm10.csv")
#kr_pm25 <- get_stat_measurements(Karlsruhe, PM25)
#write.csv(kr_pm25, "./csv/kr_pm25.csv")
kr_pm10 <- read.csv("./csv/kr_10.csv") %>% mutate(phenomena = "PM10")
kr_pm25 <- read.csv("./csv/kr_25.csv") %>% mutate(phenomena = "PM25")
kr_pm <- bind_rows(kr_pm10, kr_pm25) %>% group_by(phenomena)

#kr_pm10s <- get_stat_measurements_si(Karlsruhe, PM10)
#write.csv(kr_pm10s, "./csv/kr_pm10s.csv")
#kr_pm25s <- get_stat_measurements_si(Karlsruhe, PM25)
#write.csv(kr_pm25s, "./csv/kr_pm25s.csv")
kr_pm10s <- read.csv("./csv/kr_pm10s.csv") %>% mutate(phenomena = "PM10")
kr_pm25s <- read.csv("./csv/kr_pm25s.csv") %>% mutate(phenomena = "PM25")
kr_pms <- bind_rows(kr_pm10s, kr_pm25s) %>% group_by(phenomena)

#sw_pm10 <- get_stat_measurements(Schwerin, PM10)
#write.csv(sw_pm10, "./csv/sw_pm10.csv")
#sw_pm25 <- get_stat_measurements(Schwerin, PM25)
#write.csv(sw_pm25, "./csv/sw_pm25.csv")
sw_pm10 <- read.csv("./csv/sw_10.csv") %>% mutate(phenomena = "PM10")
sw_pm25 <- read.csv("./csv/sw_25.csv") %>% mutate(phenomena = "PM25")
sw_pm <- bind_rows(sw_pm10, sw_pm25) %>% group_by(phenomena)

#sw_pm10s <- get_stat_measurements_si(Schwerin, PM10)
#write.csv(sw_pm10s, "./csv/sw_pm10s.csv")
#sw_pm25s <- get_stat_measurements_si(Schwerin, PM25)
#write.csv(sw_pm25s, "./csv/sw_pm25s.csv")
sw_pm10s <- read.csv("./csv/sw_pm10s.csv") %>% mutate(phenomena = "PM10")
sw_pm25s <- read.csv("./csv/sw_pm25s.csv") %>% mutate(phenomena = "PM25")
sw_pms <- bind_rows(sw_pm10s, sw_pm25s) %>% group_by(phenomena)


#rb_pm10 <- get_stat_measurements(Regensburg, PM10)
#write.csv(rb_pm10, "./csv/rb_pm10.csv")
#rb_pm25 <- get_stat_measurements(Regensburg, PM25)
#write.csv(rb_pm25, "./csv/rb_pm25.csv")
rb_pm10 <- read.csv("./csv/rb_10.csv") %>% mutate(phenomena = "PM10")
rb_pm25 <- read.csv("./csv/rb_25.csv") %>% mutate(phenomena = "PM25")
rb_pm <- bind_rows(rb_pm10, rb_pm25) %>% group_by(phenomena)

#rb_pm10s <- get_stat_measurements_si(Regensburg, PM10)
#write.csv(rb_pm10s, "./csv/rb_pm10s.csv")
#rb_pm25s <- get_stat_measurements_si(Regensburg, PM25)
#write.csv(rb_pm25s, "./csv/rb_pm25s.csv")
rb_pm10s <- read.csv("./csv/rb_pm10s.csv") %>% mutate(phenomena = "PM10")
rb_pm25s <- read.csv("./csv/rb_pm25s.csv") %>% mutate(phenomena = "PM25")
rb_pms <- bind_rows(rb_pm10s, rb_pm25s) %>% group_by(phenomena)


#fl_pm10 <- get_stat_measurements(Flensburg, PM10)
#write.csv(fl_pm10, "./csv/fl_pm10.csv")
#fl_pm25 <- get_stat_measurements(Flensburg, PM25)
#write.csv(fl_pm25, "./csv/fl_pm25.csv")
fl_pm10 <- read.csv("./csv/fl_10.csv") %>% mutate(phenomena = "PM10")
fl_pm25 <- read.csv("./csv/fl_25.csv") %>% mutate(phenomena = "PM25")
fl_pm <- bind_rows(fl_pm10, fl_pm25) %>% group_by(phenomena)

#fl_pm10s <- get_stat_measurements_si(Flensburg, PM10)
#write.csv(fl_pm10s, "./csv/fl_pm10s.csv")
#fl_pm25s <- get_stat_measurements_si(Flensburg, PM25)
#write.csv(fl_pm25s, "./csv/fl_pm25s.csv")
fl_pm10s <- read.csv("./csv/fl_pm10s.csv") %>% mutate(phenomena = "PM10")
fl_pm25s <- read.csv("./csv/fl_pm25s.csv") %>% mutate(phenomena = "PM25")
fl_pms <- bind_rows(fl_pm10s, fl_pm25s) %>% group_by(phenomena)





